### PR TITLE
Support persistent-2.12 and 2.13

### PR DESCRIPTION
**Pull request by parsonsmatt**

### CODE REVIEW

**Comment by hdgarrood** [comment]
This looks good to me, although I'd be tempted to just drop support for 2.12 so that we don't need to have CPP. (Aside: I'm not really sure who the maintainer of persistent-documentation should be now, do you have a preference?)

**Comment by parsonsmatt** [comment]
I don't have access to the repository on GitHub, but I am the Hackage maintainer. I can add one of y'all to the Hackage maintainer group, or you can give me access to this repository. I'm happy either way.

**Comment by codedmart** [comment]
I am also happy to drop 2.12 so we don't need CPP. It was unintentional that you lost access to this repo. You should have access again.

**Comment by parsonsmatt** [comment]
I switched CI over to GitHub Actions but it does not appear to be running. I think y'all may need to set it up?

I'm going to run the tests on various GHC versions locally, just to make sure it's working, and then I'll merge and release.

**Comment by hdgarrood** [comment]
I think it might be a permissions thing, which is weird since you now have access... but I just pushed a commit with a `.github/workflows/demo.yml` file and the action did run. Maybe it will run if you merge main and retry?

**Pull request merged**
